from __future__ import annotations

import argparse
import importlib.util
import json
import random
import sys
import tempfile
import time
from dataclasses import asdict
from pathlib import Path
from types import ModuleType
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CASES = ROOT / "evals" / "conversation_library_cases.json"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from agent.conversations.library import DEFAULT_SEARCH_WEIGHTS, SearchWeights, build_conversation_library, organize_conversation, search_conversations


WEIGHT_NAMES = tuple(asdict(DEFAULT_SEARCH_WEIGHTS))


def load_cases(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def evaluate(cases: dict[str, Any], weights: SearchWeights) -> dict[str, Any]:
    conversations = {item["id"]: item for item in cases["conversations"]}
    classification_scores: list[float] = []
    classification_misses: list[str] = []
    for case in cases["classification"]:
        result = organize_conversation(conversations[case["id"]])
        checks = [
            result["space_id"] == case["space"],
            result["topic_id"] == case["topic"],
            set(result["sources"]) == set(case["sources"]),
        ]
        classification_scores.append(sum(checks) / len(checks))
        if not all(checks):
            classification_misses.append(case["id"])

    library = build_conversation_library(conversations.values())
    organized = {item["id"]: item["organization"] for item in library["conversations"]}
    for case in cases.get("dynamic_spaces", []):
        checks = [organized[conversation_id]["space_id"] == case["space"] for conversation_id in case["ids"]]
        classification_scores.extend(float(check) for check in checks)
        if not all(checks):
            classification_misses.extend(conversation_id for conversation_id, check in zip(case["ids"], checks) if not check)

    search_scores: list[float] = []
    search_misses: list[dict[str, Any]] = []
    corpus = list(conversations.values())
    for case in cases["search"]:
        hits = search_conversations(corpus, case["query"], weights=weights, limit=10)
        ids = [hit["id"] for hit in hits]
        rank = ids.index(case["expected_first"]) + 1 if case["expected_first"] in ids else 0
        search_scores.append(1.0 / rank if rank else 0.0)
        if rank != 1:
            search_misses.append({"query": case["query"], "expected": case["expected_first"], "rank": rank, "top": ids[:3]})

    segment_scores: list[float] = []
    for case in cases.get("segmentation", []):
        result = organize_conversation(conversations[case["id"]])
        actual = [segment["space_id"] for segment in result["segments"]]
        segment_scores.append(float(actual == case["expected_spaces"]))

    classification = sum(classification_scores) / max(len(classification_scores), 1)
    search = sum(search_scores) / max(len(search_scores), 1)
    segmentation = sum(segment_scores) / max(len(segment_scores), 1)
    overall = (classification * 0.35) + (search * 0.5) + (segmentation * 0.15)
    return {
        "score": round(overall, 6),
        "classification": round(classification, 6),
        "search": round(search, 6),
        "segmentation": round(segmentation, 6),
        "classification_misses": classification_misses,
        "search_misses": search_misses,
    }


def generate_candidate_source(weights: dict[str, float], generation: int, rationale: str) -> str:
    values = ",\n    ".join(f'"{name}": {weights[name]:.6f}' for name in WEIGHT_NAMES)
    return (
        "# Generated by the bounded Conversation Library outer loop.\n"
        f"GENERATION = {generation}\n"
        f"RATIONALE = {rationale!r}\n"
        "SEARCH_WEIGHTS = {\n    " + values + "\n}\n"
    )


def load_candidate(path: Path) -> ModuleType:
    spec = importlib.util.spec_from_file_location(f"conversation_candidate_{path.stem}", path)
    if spec is None or spec.loader is None:
        raise RuntimeError("Candidate strategy could not be loaded.")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def mutation_plan(trace: dict[str, Any], rng: random.Random, stalled: int) -> tuple[dict[str, float], str]:
    misses = trace.get("search_misses") or []
    if misses:
        queries = " ".join(str(item.get("query") or "") for item in misses).casefold()
        if any(source in queries for source in ("calendar", "slack", "spotify")):
            return {"source_term": rng.choice((0.8, 1.6, 3.2))}, "Increase connected-source recall after a source miss."
        if stalled >= 12:
            return {
                "message_term": rng.choice((8.0, 10.0, 14.0)),
                "title_term": rng.choice((-1.0, -2.0, -3.0)),
                "label_term": rng.choice((-2.0, -3.0, -4.0)),
            }, "A title-heavy strategy stalled; move weight toward the remembered message content."
        if any(len(str(item.get("query") or "").split()) >= 3 for item in misses):
            return {"exact_phrase": rng.choice((0.5, 1.0, 1.5))}, "Probe phrase precision for specific remembered wording."
        name = rng.choice(("title_term", "label_term", "message_term"))
        return {name: rng.choice((0.5, 1.0, 2.0))}, "Rebalance the field responsible for a missed result."
    name = rng.choice(WEIGHT_NAMES)
    return {name: rng.choice((-0.2, -0.1, 0.1, 0.2))}, "Probe a nearby strategy after the current corpus is solved."


def run_loop(cases: dict[str, Any], *, budget_seconds: float, seed: int, output: Path | None) -> dict[str, Any]:
    rng = random.Random(seed)
    started = time.monotonic()
    baseline_weights = asdict(DEFAULT_SEARCH_WEIGHTS)
    baseline_trace = evaluate(cases, DEFAULT_SEARCH_WEIGHTS)
    best_weights = dict(baseline_weights)
    best_trace = baseline_trace
    accepted = 0
    rejected = 0
    stalled = 0
    generation = 0

    with tempfile.TemporaryDirectory(prefix="vellum-conversation-loop-") as temp_dir:
        temp_root = Path(temp_dir)
        while time.monotonic() - started < max(0.05, budget_seconds):
            generation += 1
            updates, rationale = mutation_plan(best_trace, rng, stalled)
            candidate_values = dict(best_weights)
            for name, delta in updates.items():
                candidate_values[name] = max(0.0, candidate_values[name] + delta)
            candidate_path = temp_root / f"candidate_{generation:06d}.py"
            candidate_path.write_text(generate_candidate_source(candidate_values, generation, rationale), encoding="utf-8")
            candidate_module = load_candidate(candidate_path)
            candidate_weights = SearchWeights.from_mapping(candidate_module.SEARCH_WEIGHTS)
            trace = evaluate(cases, candidate_weights)
            if trace["score"] > best_trace["score"]:
                best_weights = dict(candidate_module.SEARCH_WEIGHTS)
                best_trace = trace
                accepted += 1
                stalled = 0
            else:
                rejected += 1
                stalled += 1
            if generation % 250 == 0:
                print(json.dumps({"generation": generation, "best_score": best_trace["score"], "accepted": accepted, "rejected": rejected}), flush=True)

    result = {
        "budget_seconds": round(time.monotonic() - started, 3),
        "generations": generation,
        "accepted": accepted,
        "rejected": rejected,
        "improved": best_trace["score"] > baseline_trace["score"],
        "baseline": {"weights": baseline_weights, "trace": baseline_trace},
        "best": {"weights": best_weights, "trace": best_trace},
    }
    if output:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description="Bounded inner/outer evaluation loop for Conversation Library search.")
    parser.add_argument("--cases", type=Path, default=DEFAULT_CASES)
    parser.add_argument("--budget-seconds", type=float, default=300.0)
    parser.add_argument("--seed", type=int, default=17)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    result = run_loop(load_cases(args.cases), budget_seconds=args.budget_seconds, seed=args.seed, output=args.output)
    print(json.dumps(result, indent=2), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
