import importlib.util
import json
import sys
from pathlib import Path


SCRIPT_PATH = Path(__file__).resolve().parents[2] / "scripts" / "import_youtube_transcripts.py"


def load_importer():
    assert SCRIPT_PATH.exists(), "scripts/import_youtube_transcripts.py should exist"
    spec = importlib.util.spec_from_file_location("import_youtube_transcripts", SCRIPT_PATH)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_channel_registry_includes_frequent_youtube_channels():
    youtube_importer = load_importer()

    assert set(youtube_importer.CHANNELS) >= {
        "moresidemen",
        "ksi",
        "sidemen",
        "betasquad",
        "matarmstrong",
    }


def test_channel_index_and_agent_guide_use_library_youtube_links(tmp_path):
    youtube_importer = load_importer()
    channel = youtube_importer.CHANNELS["betasquad"]
    base = tmp_path / "Library" / "Youtube" / "channels" / channel.key
    base.mkdir(parents=True)

    youtube_importer.write_channel_index(base, channel, [], "2026-05-18T10:00:00+00:00")
    youtube_importer.write_agent_guide(base, channel, [])

    index = (base / "_index.md").read_text(encoding="utf-8")
    guide = (base / "agent-guide.md").read_text(encoding="utf-8")

    assert "[[Library/Youtube/channels/betasquad/latest-5|Latest 5]]" in index
    assert "[[Library/Youtube/channels/betasquad/agent-guide|Agent Guide]]" in index
    assert "Current ingestion scope is Beta Squad when this channel is selected." in guide


def test_video_note_path_uses_year_date_video_id_and_slug(tmp_path):
    youtube_importer = load_importer()
    video = youtube_importer.YouTubeVideo(
        video_id="abc123XYZ09",
        title="MoreSidemen Try Not To Laugh!",
        url="https://www.youtube.com/watch?v=abc123XYZ09",
        channel="MoreSidemen",
        handle="moresidemen",
        published_at="2026-05-01T12:00:00Z",
        duration="00:20:00",
        transcript="hello world",
        language="en",
        is_auto_generated=False,
    )

    path = youtube_importer.canonical_note_path(tmp_path, video)

    assert path == tmp_path / "videos" / "2026" / "2026-05-01-abc123XYZ09-moresidemen-try-not-to-laugh.md"


def test_note_markdown_contains_required_frontmatter():
    youtube_importer = load_importer()
    video = youtube_importer.YouTubeVideo(
        video_id="abc123XYZ09",
        title="A Video",
        url="https://www.youtube.com/watch?v=abc123XYZ09",
        channel="MoreSidemen",
        handle="moresidemen",
        published_at="2026-05-01",
        duration="1200",
        transcript="hello world",
        language="en",
        is_auto_generated=True,
    )

    markdown = youtube_importer.note_markdown(video, "2026-05-14T10:00:00+00:00")

    assert "type: youtube_transcript" in markdown
    assert "channel: MoreSidemen" in markdown
    assert "handle: moresidemen" in markdown
    assert 'video_id: "abc123XYZ09"' in markdown
    assert "is_auto_generated: true" in markdown
    assert f'transcript_hash: "{video.transcript_hash}"' in markdown
    assert "## Transcript" in markdown
    assert "hello world" in markdown


def test_run_writes_deduped_notes_indexes_manifest_and_state(tmp_path):
    youtube_importer = load_importer()
    calls = []

    def fake_fetcher(channel_config, max_videos, video_type, actor, token):
        calls.append((channel_config.key, max_videos, video_type, actor, token))
        return [
            {
                "videoId": "first123456",
                "title": "First Video",
                "url": "https://www.youtube.com/watch?v=first123456",
                "channel": "MoreSidemen",
                "publishedAt": "2026-05-01T12:00:00Z",
                "duration": "00:20:00",
                "transcript": "first transcript",
                "transcriptLanguage": "en",
                "isAutoGenerated": False,
            },
            {
                "video_id": "first123456",
                "title": "First Video Duplicate",
                "url": "https://www.youtube.com/watch?v=first123456",
                "channelName": "MoreSidemen",
                "published_at": "2026-05-01T12:00:00Z",
                "duration": "00:20:00",
                "transcriptText": "duplicate transcript",
            },
            {
                "videoId": "missing1234",
                "title": "Missing Transcript",
                "url": "https://www.youtube.com/watch?v=missing1234",
                "channel": "MoreSidemen",
                "publishedAt": "2026-05-02T12:00:00Z",
                "duration": "00:22:00",
                "transcript": "",
            },
            {"title": "Malformed"},
        ]

    result = youtube_importer.run(
        project_root=tmp_path,
        channel_key="moresidemen",
        max_videos=5,
        video_type="long",
        dry_run=False,
        fetcher=fake_fetcher,
        token="test-token",
        actor="test/actor",
    )

    base = tmp_path / "Vault" / "Library" / "Youtube" / "channels" / "moresidemen"
    notes = list((base / "videos" / "2026").glob("*.md"))
    records = [json.loads(line) for line in (base / "moresidemen-transcripts.jsonl").read_text(encoding="utf-8").splitlines()]
    state = json.loads((base / ".state" / "youtube_scraper_state.json").read_text(encoding="utf-8"))

    assert result == 0
    assert calls == [("moresidemen", 5, "long", "test/actor", "test-token")]
    assert len(notes) == 1
    assert records[0]["video_id"] == "first123456"
    assert records[0]["note_path"].startswith("Library/Youtube/channels/moresidemen/videos/2026/")
    assert "First Video" in (base / "latest-5.md").read_text(encoding="utf-8")
    assert "Use these transcripts" in (base / "agent-guide.md").read_text(encoding="utf-8")
    assert state["added_count"] == 1
    assert state["skipped_count"] == 2
    assert state["duplicate_count"] == 1


def test_dry_run_does_not_write_vault_files(tmp_path):
    youtube_importer = load_importer()
    def fake_fetcher(channel_config, max_videos, video_type, actor, token):
        return [
            {
                "videoId": "first123456",
                "title": "First Video",
                "url": "https://www.youtube.com/watch?v=first123456",
                "channel": "MoreSidemen",
                "publishedAt": "2026-05-01T12:00:00Z",
                "duration": "00:20:00",
                "transcript": "first transcript",
            }
        ]

    result = youtube_importer.run(
        project_root=tmp_path,
        channel_key="moresidemen",
        max_videos=5,
        video_type="long",
        dry_run=True,
        fetcher=fake_fetcher,
        token="test-token",
        actor="test/actor",
    )

    assert result == 0
    assert not (tmp_path / "Vault" / "Library" / "Youtube").exists()


def test_run_limits_to_requested_video_count(tmp_path):
    youtube_importer = load_importer()

    def fake_fetcher(channel_config, max_videos, video_type, actor, token):
        return [
            {
                "videoId": f"video{i:06d}",
                "title": f"Video {i}",
                "url": f"https://www.youtube.com/watch?v=video{i:06d}",
                "channel": "MoreSidemen",
                "publishedAt": f"2026-05-{i + 1:02d}T12:00:00Z",
                "duration": "00:20:00",
                "transcript": f"transcript {i}",
            }
            for i in range(7)
        ]

    result = youtube_importer.run(
        project_root=tmp_path,
        channel_key="moresidemen",
        max_videos=5,
        video_type="long",
        dry_run=False,
        fetcher=fake_fetcher,
        token="test-token",
        actor="test/actor",
    )

    base = tmp_path / "Vault" / "Library" / "Youtube" / "channels" / "moresidemen"
    records = [json.loads(line) for line in (base / "moresidemen-transcripts.jsonl").read_text(encoding="utf-8").splitlines()]

    assert result == 0
    assert len(records) == 5
